name: Generate pages & deploy the blog

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  convert-to-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Generate the blog
        run: bun run index.ts

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs  # or ./dist, ./public, etc.

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
