name: pipeline

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  convert-to-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependensies
        run: npm ci
        
      - name: Run conversion script
        run: npm run start

      - name: Set up git
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./docs

      - name: Check for updated files
        id: git-status
        shell: bash
        run: |
          # echo 'GIT_STATUS<<EOF' >> $GITHUB_ENV
          # git status >> $GITHUB_ENV
          # echo 'EOF' >> $GITHUB_ENV
          echo 'SHOULD_COMMIT=contains($(git status), "Changes to be committed")' >> $GITHUB_ENV

      - name: Commit files
        if: env.SHOULD_COMMIT
        run: |
          git commit -m "Autogenerate converted pages"

      # git commit -m "Autogenerate HTML content"
      # - name: Push changes
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    force: true
