name: pipeline

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  convert-to-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run start

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./docs
          git commit -m "Autogenerate HTML content"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
